stages:
  - deploy

deploy:
  stage: deploy
  script:
    - |
      if [ ! -d "/home/gitlab-runner/ankiweb/.git" ]; then
        git clone git@gitlab.j551n.com:j551n/anki-card-creator.git /home/gitlab-runner/ankiweb
      else
        cd /home/gitlab-runner/ankiweb && git pull origin main
      fi
    - cd /home/gitlab-runner/ankiweb
    - docker compose stop anki-card-creator || true  # Stop the service if running
    - docker compose up --build -d
    - docker tag ankiweb-anki-card-creator:latest repo.j551n.com/library/anki-card-creator:$CI_PIPELINE_ID
    - docker login repo.j551n.com -u ${REPO_USERNAME} -p ${REPO_PASSWORD}
    - docker push repo.j551n.com/j551n/anki-card-creator:$CI_PIPELINE_ID
  only:
    - main