
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "88:80"
    restart: unless-stopped
    # Optional environment variables if needed
    environment:
      - NODE_ENV=production
